import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../../src/shared/styles/globals.css'
import { ClerkProvider } from "@clerk/nextjs";
// import { Provider } from "jotai";
import Providers from "@/shared/utils/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}

        </Providers>
       
      </body>
    </html>
    </ClerkProvider>
  );
}
